---
- name: Error Handling or Exception Handling
  hosts: all
  tasks:
    - block:
       - name: Install tomcat7
         apt:
          name: tomcat7
          state: present
      rescue:
       - name: Install tomcat8
         apt:
          name: tomcat8
          state: present
      always:
       - name: Check url response
         uri:
          url: "{{item}}"
          status_code: 200
         with_items:
          - http://172.31.55.129:9090
          - http://172.31.48.61:9090
...


