---
# handlers file for tomcat
- name: Check_url_response
  pause:
   minute: 4
- uri:
   url: "{{item.a}}"
   status_code: "{{item.b}}"
  with_items:
   - {a: "{{server1}}",b: "{{status1}}"}
   - {a: "{{server2}}",b: "{{status1}}"}
   - {a: "{{server3}}",b: "{{status1}}"}
...
